components:
  schemas:
    Channel:
      properties:
        description:
          title: Description
          type: string
        item:
          items:
            $ref: '#/components/schemas/Item'
          title: Item
          type: array
        link:
          title: Link
          type: string
        title:
          title: Title
          type: string
      required:
      - title
      - link
      - description
      - item
      title: Channel
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    Item:
      properties:
        description:
          anyOf:
          - type: string
          - type: 'null'
          title: Description
        link:
          anyOf:
          - type: string
          - type: 'null'
          title: Link
        pubDate:
          format: date-time
          title: Pubdate
          type: string
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
      required:
      - title
      - link
      - description
      - pubDate
      title: Item
      type: object
    Rss:
      properties:
        channel:
          $ref: '#/components/schemas/Channel'
        version:
          anyOf:
          - type: string
          - type: 'null'
          title: Version
      required:
      - channel
      title: Rss
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.1.0
paths:
  /api/v1/rss/:
    get:
      description: "Get all RSS feeds\n\nargs:\n    until: Optional[datetime] = get\
        \ all feeds until this date, default is now - 7 days"
      operationId: rss_feeds_api_v1_rss__get
      parameters:
      - in: query
        name: until
        required: false
        schema:
          anyOf:
          - format: date-time
            type: string
          - type: 'null'
          title: Until
      - in: query
        name: tag
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          default: All
          title: Tag
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Rss'
                title: Response Rss Feeds Api V1 Rss  Get
                type: array
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Rss Feeds
      tags:
      - V1
  /api/v1/rss/preview:
    get:
      operationId: rss_preview_api_v1_rss_preview_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Rss Preview
      tags:
      - V1
  /api/v1/rss/tags:
    get:
      operationId: rss_tags_api_v1_rss_tags_get
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  type: string
                title: Response Rss Tags Api V1 Rss Tags Get
                type: array
          description: Successful Response
      summary: Rss Tags
      tags:
      - V1
  /liveness:
    get:
      operationId: liveness_liveness_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Liveness
      tags:
      - ''
