services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: cmmeyer1800/myrss-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./conf.yaml:/conf.yaml

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: cmmeyer1800/myrss-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    command: npm run dev -- --host 0.0.0.0

  router:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf