// This file is auto-generated by @hey-api/openapi-ts

export const ChannelSchema = {
    properties: {
        description: {
            title: 'Description',
            type: 'string'
        },
        item: {
            items: {
                '$ref': '#/components/schemas/Item'
            },
            title: 'Item',
            type: 'array'
        },
        link: {
            title: 'Link',
            type: 'string'
        },
        title: {
            title: 'Title',
            type: 'string'
        }
    },
    required: ['title', 'link', 'description', 'item'],
    title: 'Channel',
    type: 'object'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            title: 'Detail',
            type: 'array'
        }
    },
    title: 'HTTPValidationError',
    type: 'object'
} as const;

export const ItemSchema = {
    properties: {
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        link: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Link'
        },
        pubDate: {
            format: 'date-time',
            title: 'Pubdate',
            type: 'string'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        }
    },
    required: ['title', 'link', 'description', 'pubDate'],
    title: 'Item',
    type: 'object'
} as const;

export const RssSchema = {
    properties: {
        channel: {
            '$ref': '#/components/schemas/Channel'
        },
        version: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Version'
        }
    },
    required: ['channel'],
    title: 'Rss',
    type: 'object'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            title: 'Location',
            type: 'array'
        },
        msg: {
            title: 'Message',
            type: 'string'
        },
        type: {
            title: 'Error Type',
            type: 'string'
        }
    },
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError',
    type: 'object'
} as const;
